_BASE_: panoptic_affinity_pretrain.yaml
MODEL:
  FREEZE_BN: True
  TRAIN_EDGE_INDEX_START: 0
  TRAIN_EDGE_INDEX_END: 6
  FINE_TUNING_MODE: True
  FREEZE_SEM_SEG_TILL: 1
  FREEZE_EDGE_COSTS_TILL: 1
  PANOPTIC_AFFINITY:
    LAMBDA_VAL_START: 1.0
    LAMBDA_VAL_END: 5000.0
    AMC_LOSS_WEIGHT: 10.0
    STUFF_AREA: 2048
    INSTANCE_AREA: 200
    EVAL_PQ_DURING_TRAIN: True
    TARGET_DOWNSAMPLING: 4
  SEM_SEG_HEAD:
    LOSS_WEIGHT: 0.0
    NORM: "BN"
  AFF_EMBED_HEAD:
    AFF_LOSS_WEIGHT: 0.0
    NORM: "BN"
SOLVER:
  OPTIMIZER: "ADAM"
  BASE_LR: 0.001
  WEIGHT_DECAY: 0.0
  WEIGHT_DECAY_NORM: 0.0
  WEIGHT_DECAY_BIAS: 0.0
  WARMUP_ITERS: 500
  MAX_ITER: 20000
  LR_SCHEDULER_NAME: "WarmupPolyLR"
  IMS_PER_BATCH: 24
  CHECKPOINT_PERIOD: 500
INPUT:
  INSTANCE_LOSS_WEIGHT: 1.0
  SMALL_INSTANCE_WEIGHT: 1
  MIN_SIZE_TRAIN: (512, 640, 704, 832, 896, 1024, 1152, 1216, 1344, 1408, 1536, 1664, 1728, 1856, 1920, 2048)
  MIN_SIZE_TRAIN_SAMPLING: "choice"
  CROP:
    ENABLED: True
    TYPE: "absolute"
    SIZE: (512, 1024)
    SINGLE_CATEGORY_MAX_AREA: 1.0
DATALOADER:
  EVAL_BATCH_SIZE: 4
  NUM_WORKERS: 0 # invest computational resources in solving AMWC.
TEST:
  EVAL_PERIOD: -1
SEED: -1
DATASETS:
  TRAIN: ("cityscapes_fine_panoptic_train",)
  TEST: ("cityscapes_fine_panoptic_val",)
OUTPUT_DIR: output/cityscapes/fully_differentiable/
VIS_PERIOD: 50
VAL_LOSS_PERIOD: -1